In [1]:
import numpy as np

In [ ]:
array_1d = np.array([1,2,3,4,5])
print(array_1d.ndim)
print(array_1d.shape)
array_1d
# Lista de dados, como séries temporais ou colecoes de valores

1
(5,)


array([1, 2, 3, 4, 5])

In [ ]:
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d.ndim)
print(array_2d.shape)
array_2d

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
array_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(array_3d.ndim)
print(array_3d.shape)
array_3d

3
(2, 2, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
array_4d = np.zeros((2,3,4,5))
print(array_4d.ndim)
print(array_4d.shape)
array_4d

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])